name: CI/CD

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send files to server
      uses: appleboy/scp-action@master
      with:
        host: 152.228.163.78
        username: debian
        password: ${{ secrets.SERVER_PASSWORD }}
        source: src/back/
        target: bankroot

    - name: Deploy to server !
      uses: appleboy/ssh-action@master
      with:
        host: 152.228.163.78
        username: debian
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /home/debian/bankroot/src/back
          docker build -t nest/bankroot:v1 .
          docker-compose up -d
